[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme tender
'''
